In [5]:
import pandas as pd
import numpy as np

# Load cleaned dataset
df = pd.read_excel("Cleaned_Sample_Dataset.xlsx")

# Basic information
print("Dataset Shape:", df.shape)

print("\nFirst 5 Rows:")
display(df.head())

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())


# Statistical Analysis
print("\n========== STATISTICAL SUMMARY ==========")
statistics = df.describe()
display(statistics)

print("\n========== MEDIAN ==========")
display(df.median(numeric_only=True))

print("\n========== STANDARD DEVIATION ==========")
display(df.std(numeric_only=True))

print("\n========== SKEWNESS ==========")
display(df.skew(numeric_only=True))

print("\n========== KURTOSIS ==========")
display(df.kurt(numeric_only=True))


# Product Analysis
product_analysis = df.groupby("product").agg(
    Total_Sales=("sales", "sum"),
    Total_Profit=("profit", "sum"),
    Total_Quantity=("quantity", "sum"),
    Average_Sales=("sales", "mean")
).sort_values("Total_Sales", ascending=False)

print("\n========== PRODUCT ANALYSIS ==========")
display(product_analysis)


# Category Analysis
category_analysis = df.groupby("category").agg(
    Total_Sales=("sales", "sum"),
    Total_Profit=("profit", "sum"),
    Total_Quantity=("quantity", "sum"),
    Average_Sales=("sales", "mean")
).sort_values("Total_Sales", ascending=False)

print("\n========== CATEGORY ANALYSIS ==========")
display(category_analysis)


# Region Analysis
region_analysis = df.groupby("region").agg(
    Total_Sales=("sales", "sum"),
    Total_Profit=("profit", "sum"),
    Total_Quantity=("quantity", "sum"),
    Average_Sales=("sales", "mean")
).sort_values("Total_Sales", ascending=False)

print("\n========== REGION ANALYSIS ==========")
display(region_analysis)


# Channel Analysis
channel_analysis = df.groupby("channel").agg(
    Total_Sales=("sales", "sum"),
    Total_Profit=("profit", "sum"),
    Total_Quantity=("quantity", "sum"),
    Average_Sales=("sales", "mean")
).sort_values("Total_Sales", ascending=False)

print("\n========== CHANNEL ANALYSIS ==========")
display(channel_analysis)


# Salesperson Analysis
salesperson_analysis = df.groupby("salesperson").agg(
    Total_Sales=("sales", "sum"),
    Total_Profit=("profit", "sum"),
    Total_Quantity=("quantity", "sum"),
    Average_Rating=("customer_rating", "mean")
).sort_values("Total_Sales", ascending=False)

print("\n========== SALESPERSON ANALYSIS ==========")
display(salesperson_analysis)


# Monthly Analysis
df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")
df["month"] = df["order_date"].dt.to_period("M").astype(str)

monthly_analysis = df.groupby("month").agg(
    Total_Sales=("sales", "sum"),
    Total_Profit=("profit", "sum"),
    Total_Quantity=("quantity", "sum"),
    Total_Orders=("order_id", "nunique")
).reset_index()

print("\n========== MONTHLY ANALYSIS ==========")
display(monthly_analysis)


# Correlation Analysis
numeric_columns = [
    "quantity",
    "unit_price",
    "discount",
    "sales",
    "profit",
    "customer_rating"
]

correlation = df[numeric_columns].corr()

print("\n========== CORRELATION ANALYSIS ==========")
display(correlation)


# Key Business Metrics
total_sales = df["sales"].sum()
total_profit = df["profit"].sum()
total_orders = df["order_id"].nunique()
total_quantity = df["quantity"].sum()
average_sales = df["sales"].mean()
average_profit = df["profit"].mean()
average_rating = df["customer_rating"].mean()

summary = pd.DataFrame({
    "Metric": [
        "Total Sales",
        "Total Profit",
        "Total Orders",
        "Total Quantity",
        "Average Sales",
        "Average Profit",
        "Average Customer Rating",
        "Best Product",
        "Best Category",
        "Best Region",
        "Best Channel",
        "Best Salesperson"
    ],
    "Value": [
        round(total_sales, 2),
        round(total_profit, 2),
        total_orders,
        total_quantity,
        round(average_sales, 2),
        round(average_profit, 2),
        round(average_rating, 2),
        product_analysis["Total_Sales"].idxmax(),
        category_analysis["Total_Sales"].idxmax(),
        region_analysis["Total_Sales"].idxmax(),
        channel_analysis["Total_Sales"].idxmax(),
        salesperson_analysis["Total_Sales"].idxmax()
    ]
})

print("\n========== KEY BUSINESS METRICS ==========")
display(summary)


# Top 10 Orders
top_10_orders = df.sort_values(
    "sales",
    ascending=False
).head(10)

print("\n========== TOP 10 ORDERS ==========")
display(top_10_orders)


# Save Analysis Results
output_file = "Python_Analysis_Results.xlsx"

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:

    df.to_excel(
        writer,
        sheet_name="Data",
        index=False
    )

    statistics.to_excel(
        writer,
        sheet_name="Statistics"
    )

    product_analysis.to_excel(
        writer,
        sheet_name="Product_Analysis"
    )

    category_analysis.to_excel(
        writer,
        sheet_name="Category_Analysis"
    )

    region_analysis.to_excel(
        writer,
        sheet_name="Region_Analysis"
    )

    channel_analysis.to_excel(
        writer,
        sheet_name="Channel_Analysis"
    )

    salesperson_analysis.to_excel(
        writer,
        sheet_name="Salesperson_Analysis"
    )

    monthly_analysis.to_excel(
        writer,
        sheet_name="Monthly_Analysis",
        index=False
    )

    correlation.to_excel(
        writer,
        sheet_name="Correlation"
    )

    summary.to_excel(
        writer,
        sheet_name="Summary",
        index=False
    )

    top_10_orders.to_excel(
        writer,
        sheet_name="Top_10_Orders",
        index=False
    )

print("\n====================================")
print("ANALYSIS COMPLETED SUCCESSFULLY")
print("====================================")
print("Output file: Python_Analysis_Results.xlsx")
print("Refresh the Colab Files panel to see the file.")

Dataset Shape: (120, 13)

First 5 Rows:

,order_id,order_date,product,category,region,channel,salesperson,quantity,unit_price,discount,sales,profit,customer_rating
0,ORD1001,2025-01-01 00:00:00.000,Keyboard,Accessories,South,Store,Priya,3,2500,0.19,6075,979.36,3.4
1,ORD1002,2025-01-02 12:18:09.076,Office Chair,Furniture,North,Online,Sneha,1,12000,0.18,9840,925.86,3.8
2,ORD1003,2025-01-04 00:36:18.151,Monitor,Electronics,West,Online,Priya,2,18000,0.05,34200,5807.94,3.7
3,ORD1004,2025-01-05 12:54:27.227,Office Chair,Furniture,East,Online,Sneha,7,12000,0.00,84000,12950.88,4.0
4,ORD1005,2025-01-07 01:12:36.303,Office Chair,Furniture,East,Online,Rahul,6,12000,0.19,58320,12618.03,3.5

Column Names:
['order_id', 'order_date', 'product', 'category', 'region', 'channel', 'salesperson', 'quantity', 'unit_price', 'discount', 'sales', 'profit', 'customer_rating']

Data Types:
order_id                   object
order_date         datetime64[ns]
product                    object
category                   object
region                     object
channel                    object
salesperson                object
quantity                    int64
unit_price                  int64
discount                  float64
sales                       int64
profit                    float64
customer_rating           float64
dtype: object

Missing Values:
order_id           0
order_date         0
product            0
category           0
region             0
channel            0
salesperson        0
quantity           0
unit_price         0
discount           0
sales              0
profit             0
customer_rating    0
dtype: int64

Duplicate Rows:
0

========== STATISTICAL SUMMARY ==========

,order_date,quantity,unit_price,discount,sales,profit,customer_rating
count,120,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000
mean,2025-04-01 09:04:32.268908288,4.700000,21700.000000,0.109333,86270.041667,14410.379167,3.753333
min,2025-01-01 00:00:00,1.000000,2500.000000,0.000000,2025.000000,213.370000,2.500000
25%,2025-02-16 03:13:36.807000064,3.000000,9000.000000,0.070000,16493.750000,2676.507500,3.300000
50%,2025-04-01 18:09:04.537999872,5.000000,12000.000000,0.110000,55200.000000,8139.095000,3.800000
75%,2025-05-16 00:00:00,6.000000,30000.000000,0.150000,123585.000000,17185.385000,4.300000
max,2025-06-30 00:00:00,8.000000,65000.000000,0.190000,418600.000000,92035.810000,5.000000
std,NaN,2.187051,20932.103124,0.053746,92960.137057,17530.359767,0.673126

========== MEDIAN ==========

quantity               5.000
unit_price         12000.000
discount               0.110
sales              55200.000
profit              8139.095
customer_rating        3.800
dtype: float64

========== STANDARD DEVIATION ==========

quantity               2.187051
unit_price         20932.103124
discount               0.053746
sales              92960.137057
profit             17530.359767
customer_rating        0.673126
dtype: float64

========== SKEWNESS ==========

quantity          -0.211155
unit_price         1.214413
discount          -0.173306
sales              1.630715
profit             2.081977
customer_rating   -0.099728
dtype: float64

========== KURTOSIS ==========

quantity          -1.066303
unit_price         0.205580
discount          -1.030950
sales              2.242718
profit             4.491464
customer_rating   -0.900100
dtype: float64

========== PRODUCT ANALYSIS ==========

              Total_Sales  Total_Profit  Total_Quantity  Average_Sales
product
Laptop            4415720     801013.73              82  220786.000000
Smartphone        2950800     442513.86             111  140514.285714
Monitor           1135260     186755.52              71   70953.750000
Office Chair       942000     156940.66              87   49578.947368
Desk               602100      91624.25              79   37631.250000
Keyboard           306525      50397.48             134   10947.321429

========== CATEGORY ANALYSIS ==========

             Total_Sales  Total_Profit  Total_Quantity  Average_Sales
category
Electronics      8448860    1419238.50             258  150872.500000
Furniture        1597020     259609.52             172   44361.666667
Accessories       306525      50397.48             134   10947.321429

========== REGION ANALYSIS ==========

        Total_Sales  Total_Profit  Total_Quantity  Average_Sales
region
North       3075200     587009.76             129  102506.666667
East        2798495     410890.63             203   75635.000000
West        2663795     428935.73             129   91855.000000
South       1814915     302409.38             103   75621.458333

========== CHANNEL ANALYSIS ==========

         Total_Sales  Total_Profit  Total_Quantity  Average_Sales
channel
Store        5219505     910067.14             284   85565.655738
Online       5132900     819178.36             280   86998.305085

========== SALESPERSON ANALYSIS ==========

             Total_Sales  Total_Profit  Total_Quantity  Average_Rating
salesperson
Amit             2307340     408377.06             102        3.790909
Priya            1941725     317572.19              85        3.768421
Rahul            1748975     296659.72             102        3.615789
Vikas            1716780     317288.89              75        3.782353
Neha             1534735     218664.32              83        3.794444
Sneha            1102850     170683.32             117        3.764000

========== MONTHLY ANALYSIS ==========

     month  Total_Sales  Total_Profit  Total_Quantity  Total_Orders
0  2025-01      1141635     194559.82              90            21
1  2025-02      1552070     245051.00              96            18
2  2025-03      1677325     282864.42              84            20
3  2025-04      1459100     238932.79             100            21
4  2025-05      1520075     287987.88              98            20
5  2025-06      3002200     479849.59              96            20

========== CORRELATION ANALYSIS ==========

,quantity,unit_price,discount,sales,profit,customer_rating
quantity,1.000000,-0.100371,-0.101802,0.349759,0.312949,-0.031852
unit_price,-0.100371,1.000000,0.040829,0.802651,0.764740,0.171301
discount,-0.101802,0.040829,1.000000,0.012211,0.074587,0.020038
sales,0.349759,0.802651,0.012211,1.000000,0.931808,0.143464
profit,0.312949,0.764740,0.074587,0.931808,1.000000,0.171942
customer_rating,-0.031852,0.171301,0.020038,0.143464,0.171942,1.000000

========== KEY BUSINESS METRICS ==========

                     Metric        Value
0               Total Sales     10352405
1              Total Profit    1729245.5
2              Total Orders          120
3            Total Quantity          564
4             Average Sales     86270.04
5            Average Profit     14410.38
6   Average Customer Rating         3.75
7              Best Product       Laptop
8             Best Category  Electronics
9               Best Region        North
10             Best Channel        Store
11         Best Salesperson         Amit

========== TOP 10 ORDERS ==========

,order_id,order_date,product,category,region,channel,salesperson,quantity,unit_price,discount,sales,profit,customer_rating,month
111,ORD1112,2025-06-17 21:34:47.395,Laptop,Electronics,West,Store,Amit,7,65000,0.08,418600,66176.04,2.7,2025-06
98,ORD1099,2025-05-29 05:38:49.412,Laptop,Electronics,North,Store,Vikas,7,65000,0.18,373100,92035.81,4.6,2025-05
28,ORD1029,2025-02-12 08:28:14.118,Laptop,Electronics,North,Store,Priya,6,65000,0.07,362700,68900.02,3.8,2025-02
102,ORD1103,2025-06-04 06:51:25.714,Laptop,Electronics,West,Online,Neha,6,65000,0.07,362700,34627.10,4.6,2025-06
101,ORD1102,2025-06-02 18:33:16.639,Laptop,Electronics,South,Store,Rahul,6,65000,0.12,343200,59826.16,3.7,2025-06
104,ORD1105,2025-06-07 07:27:43.866,Laptop,Electronics,East,Online,Vikas,5,65000,0.10,292500,50621.77,4.9,2025-06
21,ORD1022,2025-02-01 18:21:10.588,Laptop,Electronics,North,Online,Amit,5,65000,0.13,282750,66613.99,4.7,2025-02
53,ORD1054,2025-03-22 04:02:01.008,Laptop,Electronics,North,Online,Rahul,5,65000,0.15,276250,68371.50,4.3,2025-03
116,ORD1117,2025-06-25 11:05:32.773,Laptop,Electronics,West,Store,Priya,5,65000,0.15,276250,51254.59,3.4,2025-06
80,ORD1081,2025-05-02 00:12:06.050,Smartphone,Electronics,East,Online,Amit,8,30000,0.01,237600,29860.22,3.4,2025-05

====================================
ANALYSIS COMPLETED SUCCESSFULLY
====================================
Output file: Python_Analysis_Results.xlsx
Refresh the Colab Files panel to see the file.